schema_version = "1.0.0"
id = "ChannelOffset"
version = "3.0.0"
name = "Channel Offset"
tagline = "Offsets all the keyframes on a channel"
maintainer = "Blender Bob"
type = "add-on"
website = "https://github.com/riouxr/Curve-Offset"
tags = ["Animation"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Robert Rioux"]